#
# Makefile: Commands to simplify development and releases
#

# You can set these variable on the command line.
PYTHON = python3.8

# Where everything lives

root_dir = $(realpath .)
app_dir = $(root_dir)/src/library_project

python := $(root_dir)/venv/bin/python3
pip := $(root_dir)/venv/bin/pip3
django := $(python) $(root_dir)/manage.py
pip-compile := $(root_dir)/venv/bin/pip-compile
pip-sync := $(root_dir)/venv/bin/pip-sync
checker := $(root_dir)/venv/bin/flake8
black := $(root_dir)/venv/bin/black
isort := $(root_dir)/venv/bin/isort
pytest := $(root_dir)/venv/bin/pytest
coverage := $(root_dir)/venv/bin/coverage
bumpversion := $(root_dir)/venv/bin/bump2version
twine := $(root_dir)/venv/bin/twine


commit_opts := --gpg-sign
upload_opts := --skip-existing --sign
pytest_opts := --flake8 --black --isort

.PHONY: help
help:
	@echo "Please use 'make <target>' where <target> is one of:"
	@echo ""
	@echo "  help                 to show this list"
	@echo "  clean-build          to clean the files and directories generated by previous builds"
	@echo "  clean-tests          to clean the directories created during testing"
	@echo "  clean-coverage       to clean the test coverage data and reports"
	@echo "  clean-venv           to clean the virtualenv"
	@echo "  clean                to clean everything"
	@echo
	@echo "  build                to build the package"
	@echo "  coverage             to measure the test coverage"
	@echo "  major                to update the version number for a major release, e.g. 2.1 to 3.0"
	@echo "  messages             to run the makemessages and compilemessages management commands"
	@echo "  migrate              to run migrate management command"
	@echo "  migrations           to run makemigrations management command"
	@echo "  minor                to update the version number for a minor release, e.g. 2.1 to 2.2"
	@echo "  nightly              to build a development version of the package"
	@echo "  patch                to update the version number for a patch release, e.g. 2.1.1 to 2.1.2"
	@echo "  pretty               to reformat the app source code"
	@echo "  runserver            to run the Django demo site"
	@echo "  test                 to run the tests during development"
	@echo "  upload               to upload a release to PyPI repository"
	@echo "  venv                 to create the virtualenv and install dependencies"
	@echo "  verify               to verify the tests pass for all supported environments"
	@echo

.PHONY: clean-build
clean-build:
	rm -rf build
	rm -rf src/*.egg-info

.PHONY: clean-tests
clean-tests:
	rm -rf .toxrm -rf .pytest_cache

.PHONY: clean-coverage
clean-coverage:
	rm -rf .coverage
	rm -rf reports/coverage

.PHONY: clean-venv
clean-venv:
	rm -rf venv

.PHONE: clean-versions
clean-versions:
	rm requirements.txt

.PHONY: clean
clean: clean-build clean-tests clean-venv clean-versions

.PHONY: build
build: clean-build
	$(python) setup.py sdist bdist_wheel

.PHONY: coverage
coverage:
	pytest --cov=library_project --cov-config=setup.cfg --cov-report html

.PHONY: major
major:
	$(bumpversion) major

.PHONY: messages
messages:
	cd $(app_dir) && $(django) makemessages --no-obsolete --all && $(django) compilemessages

.PHONY: migrate
migrate:
	$(django) migrate

.PHONY: migrations
migrations:
	$(django) makemigrations

.PHONY: minor
minor:
	$(bumpversion) minor

.PHONY: nightly
nightly: clean-build
	$(python) setup.py egg_info --tag-build .dev- --tag-date sdist

.PHONY: patch
patch:
	$(bumpversion) patch

.PHONY: pretty
pretty:
	$(black) src
	$(isort) src

.PHONY: runserver
runserver: venv
	$(django) migrate
	$(django) runserver

.PHONY: test
test:
	pytest $(pytest_opts)

.PHONY: upload
upload:
	$(twine) upload $(upload_opts) dist/*

venv:
	$(PYTHON) -m venv venv
	$(pip) install --upgrade pip setuptools wheel
	$(pip) install pip-tools
	$(pip-sync)

.PHONY: verify
verify: test
	tox

# include any local makefiles
-include *.mk
